### ISSUE TITLE
fix ur shit website

### ISSUE THREAD

**Issue by naahi-rihan** [mxTuhin/KrakenFlask#4]
detection is not working

**Comment by mxTuhin** [comment]
Not at Workstation. Stuck in Storm 🥱

**Comment by mxTuhin** [comment]
![FixOfKrakenWeb](https://user-images.githubusercontent.com/28976846/195934565-cd60b544-91c6-423f-8eea-fbfffc1a05bc.png)
![DebrisTracker](https://user-images.githubusercontent.com/28976846/195934575-2b93c4bf-ab82-4523-bd5d-84b0fa422b7b.png)


Issue Has been resolved. Gimme Treat Sometime later :v

**Comment by naahi-rihan** [comment]
Treatos 🤨🤨
